source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PrimarySource_Example', :exclusive => true do
  pod "PrimarySource", :path => "../"
end

target 'PrimarySource_Tests', :exclusive => true do
  pod "PrimarySource", :path => "../"

  
end
