source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PrimarySource_Example' do
  pod "PrimarySource", :path => "../"
end

target 'PrimarySource_Tests' do
  pod "PrimarySource", :path => "../"

  
end
