source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CollectionDataSource_Example', :exclusive => true do
  pod "CollectionDataSource", :path => "../"
end

target 'CollectionDataSource_Tests', :exclusive => true do
  pod "CollectionDataSource", :path => "../"

  
end
