platform :osx, '10.11'
use_frameworks!

target 'PrimarySourceExample-OSX' do
    pod "PrimarySource", :path => "../"
end

target 'PrimarySourceExample-OSXTests' do
    pod "PrimarySource", :path => "../"
end

